ruby_version: 2.5.0
fix: false
parallel: true
ignore:
  - test/**/*
  - examples/**/*
  - myapp/**/*
  - 'lib/sidekiq/extensions/**/*':
    - Style/MethodMissingSuper
    - Style/MissingRespondToMissing
  - 'lib/**/*':
    - Naming/AsciiIdentifiers
    - Lint/RescueException
    - Security/YAMLLoad
    - Naming/AccessorMethodName
    - Naming/MethodName
    - Style/GlobalVars
    - Style/Alias
