source 'https://rubygems.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Project requirements
gem 'rake'

# Component requirements
gem 'haml'
# Sidekiq uses slim
gem 'slim'
gem 'activerecord', :require => 'active_record'
gem 'sqlite3'
gem 'sidekiq', :path => '../..'

# Optional json codecs
# gem 'yajl-ruby', :platform => 'mri'  # smaller memory footprint
# gem 'oj'                             # faster

# Test requirements

# Padrino Stable Gem
# gem 'padrino', '0.10.7'

# Or Padrino Edge
gem 'padrino', :git => 'git://github.com/padrino/padrino-framework.git'

# Or Individual Gems
# %w(core gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.10.7'
# end
