source 'https://rubygems.org'

gem 'sidekiq', :path => '..'
gem 'rails', "~> 6.1"
gem 'puma'

gem "redis-client"

# Ubuntu required packages to install rails
# apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev libsqlite3-dev
platforms :ruby do
  gem 'sqlite3'
end

gem 'after_commit_everywhere'